### ISSUE TITLE
https://www.sympa.community/help/ 404 page not found

### ISSUE THREAD

**Issue by feydreva** [sympa-community/sympa-community.github.io#101]
Hello, 

On the page : https://www.sympa.community/manual/
On the left menu : Sympa help >> https://www.sympa.community/help/ >> Page not found. 404 File not found

If you have infos on where to ask for help, I would need them :)
Thank you

**Comment by ikedas** [comment]
Thank you for reporting bug.  It was fixed. It may take a while for the modifications to be reflected throughout the site.
