### ISSUE TITLE
update link to modlist/whitelist plugin

### ISSUE THREAD

**Issue by errror** [sympa-community/sympa-community.github.io#106]
The Documentation for the modlist/whitelist plugin in `manual/customize/template-plugins-modwhitelist.md` is outdated. There is a more recent version (currently whitelist-1.2) from the same author that can be found at https://github.com/sshipway/sympa-6.2-plugins/, last update was 2021.

**Comment by ikedas** [comment]
Hi @errror , thanks for information! The link has been updated.
