### ISSUE TITLE
Telnet Example on the configure-mail-server.html#tests Section

### ISSUE THREAD

**Issue by Zwordi** [sympa-community/sympa-community.github.io#15]
Hello base on my [issue](https://github.com/sympa-community/sympa/issues/264) There is a section who could be added on the Test page: https://sympa-community.github.io/manual/install/configure-mail-server.html#tests

Telnet Example
--------------
  1. Open your favorite telnet tools (telnet or putty for example)
  
  2. Open a session to your postfix server and use this command (replace example by your lists)

  helo example.fr  
    ``250 yourserverpostfix  ``
  mail from:<userlist@example.fr>
   `` 250 2.1.0 Ok  ``
  rcpt to:<testlist@lists.example.com>
    ``250 2.1.5 Ok  ``
  DATA
  Message-ID:Something
  Sender:<userlist@example.fr>
  From:<userlist@example.fr>
  Return-Path:<userlist@example.fr>
  Subject: Hello
  Hello World
  .
    ``250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as XXXXXXXXXXXXXX  ``
  
  This should be enought to test your lists and see if everything is ok on the MTA Side.

Remember your logs:
  ``/var/log/syslog|messages``
  ``/var/log/maillog  ``
  ``/var/log/sympa.log  ``

**Comment by ikedas** [comment]
Hi @Zwordi,

Thanks for contribution.

If possible, could you please submit changes/additions as pull request or patch?

**Comment by Zwordi** [comment]
Hello @ikedas ,

I tried to do it by making a new branch but i got «Permission to sympa-community/sympa-community.github.io.git denied to Zwordi.». I may have miss something.

**Comment by ikedas** [comment]
Ok, I'll commit your change under your name.  Can you please tell us your full name (pen name is ok) and, if possible e-mail address.

**Comment by Zwordi** [comment]
Can i send it to your mail ?

**Comment by ikedas** [comment]
Yes you can.  However, your name and (if provided) email will be included in commit log, your name will be added to [AUTHORS](https://sympa-community.github.io/AUTHORS.html) file, and they are open to public.  So at least, I want to know your name (or pen name) you want to use.

**Comment by ikedas** [comment]
Hi @Zwordi,
I commited your texts, with some modification by me:
https://ikedas.github.io/sympa-community.github.io/manual/install/configure-mail-server.html#telnet-example

Thank you for your contribution!
