### ISSUE TITLE
A page is needed for contact info, mailing lists, issue tracker etc.

### ISSUE THREAD

**Issue by hmpf** [sympa-community/sympa-community.github.io#16]
The old doc has the drop down "Doc & Support". There's not much "support" on the new site yet. 

The new site needs to cover the "mailing lists" link and "technical support" link somehow, and there should be a link to the sympa github for reporting bugs. On the old site, "mailing lists" is a link to renater's own sympa, that has a lot of mailing lists. It would probably be better on the new site to have a local page with a subset of the available lists, with a short description why that list should be subscribed to: for instance "sympa-announce" should be high priority because that's where the security-advisories go currently! See also https://github.com/sympa-community/sympa/issues/271

**Comment by ikedas** [comment]
Hi @hmpf,

There are several documents available.  They will be added or liked from this documentation site in near future:
  - List of mailing lists --- Work in progress. See #17.
  - [Release notes](https://github.com/sympa-community/sympa/blob/master/CONTRIBUTING.md)
  - [Contributing to Sympa](https://github.com/sympa-community/sympa/blob/master/CONTRIBUTING.md)

Please give suggestion about anything else necessary.

**Comment by ikedas** [comment]
The issue no longer be followed.  Close.
