### ISSUE TITLE
List of lists related to Sympa community

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa-community.github.io#17]
As we discussed on irc meeting, we will add sympa mailing lists and descriptions to doc.

Below is current list of lists related to Sympa community (initially taken from category [`informatique/sympa`](https://listes.renater.fr/sympa/lists/informatique/sympa) on `listes.renater.fr` and added some).

  - Lists no longer used are ~~marked~~.

  - If I miss anything, please point it out.

----

  - ~~[`formation-sympa-2013-avances@listes.renater.fr`](https://listes.renater.fr/sympa/info/formation-sympa-2013-avances)~~

    Souhaits de formations sur les usages de base de Sympa

  - ~~[`formation-sympa-2013-bases@listes.renater.fr`](https://listes.renater.fr/sympa/info/formation-sympa-2013-bases)~~

    Souhaits de formations sur les usages de base de Sympa

  - ~~[`noustestons@listes.renater.fr`](https://listes.renater.fr/sympa/info/noustestons)~~

    Liste de test

  - ~~[`noustestons2@listes.renater.fr`](https://listes.renater.fr/sympa/info/noustestons2)~~

    Liste de test toto

  - [`sympa-announce@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-announce)

    Announce of new sympa release

    ~~(includes `sympa-users`, `sympa-dev`, `sympa-fr` and maybe `sympa-pootle`)~~
    Update 04-21: includes:
      - `sympa-fr`
      - `sympa-users`
      - `sympa-dev`
      - `sympa-packagers`
      - `sympa-es`
      - `sympa-developpers`

  - ~~[`sympa-authors@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-authors)~~

    the authors of Sympa (Étienne Méléard / David Verdin)

    (No longer used for contact to developers.  `sympa-developpers` is used instead)

  - ~~[`sympa-commits@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-commits)~~

    Sympa subversion repository modifications tracking

    (subversion repository is no longer updated)

  - ~~[`sympa-dev@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-developpers)~~

    (no longer used.  Successor is `sympa-developpers`)

  - [`sympa-developpers@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-developpers)

    the mailing list for listmasters using sympa

  - ~~[`sympa-es@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-es)~~

    Lista hispanófona de Sympa

    (practically not used)

  - [`sympa-fr@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-fr)

    Pour les administrateurs de serveurs de listes utilisant le logiciel Sympa.

  - [`sympa-hackathon-2018@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-hackathon-2018)

    registration for sympa hackathon

  - [`sympa-packagers@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-packagers)

    List for people interesting in developping and using Sympa packages

  - ~~[`sympa-pootle@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-pootle)~~

    This list gathers all the translators registered on `http://pootle.sympa.org`

    (no longer used, because older pootle site is no longer updated)

  - [`sympa-security@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-security)

    (Coming later)

  - [`sympa-users@listes.renater.fr`](https://listes.renater.fr/sympa/info/sympa-users)

    the mailing list for listmasters using sympa

**Comment by xavierba** [comment]
Looks good.
sympa-announce included lists should probably be reviewed. Should include -developpers, -users, -packagers. Possibly -fr too.

**Comment by tvo6** [comment]
Works for me too, but sympa-hackathon-2018@listes.renater.fr should be removed (as well as other "temporary" lists).

**Comment by ikedas** [comment]
According to discussion on IRC, I submitted PR above.  Please check it.

Note:
  - Additonally, I'm planning to launch a new read-only list to distribute announcements for translators (see also sympa-community/sympa#333).

**Comment by ikedas** [comment]
List described above was launched: https://translate.sympa.org/sympa/info/lets

This issue is closed.
