### ISSUE TITLE
"Configure system log" typo

### ISSUE THREAD

**Issue by rbd2rbd2** [sympa-community/sympa-community.github.io#18]
On the https://sympa-community.github.io/manual/install/configure-system-log.html page the "Create log file" section names the syslog file "syslog" but it should be "sympa.log" as in step 2.

**Comment by ikedas** [comment]
Hi @rbd2rbd2,

Indeed. Thanks for reporting typo. [Fixed](https://github.com/sympa-community/sympa-community.github.io/commit/591d5fe).
