### ISSUE TITLE
Multiple virtual hosts with nginx

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa-community.github.io#41]
[Current documentation on nginx](https://github.com/sympa-community/sympa-community.github.io/blob/aee426a2a8be47f16b5b9e964798afcff885a4f9/manual/install/configure-http-server-spawnfcgi.md#nginx) doesn't consider the case with multiple virtual hosts.

As WWSympa recognizes virtual host according to `SERVER_NAME` environment variable, it should be tweaked as:
``` code
server {
    listen      80;
    #server_name localhost.localdomain;  # Change it!
    server_name vhost1.example.org vhost2.example.com;            ← If multiple names given,

    location /sympa {
        include       /etc/nginx/fastcgi_params;
        fastcgi_pass  unix:$PIDDIR/wwsympa.socket;

        # If you changed wwsympa_url in sympa.conf, change this regex too!
        fastcgi_split_path_info ^(/sympa)(.*)$;
        fastcgi_param SCRIPT_FILENAME $EXECCGIDIR/wwsympa.fcgi;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SERVER_NAME $host;                          ← This should be added.
    }

    location /static-sympa {
        alias $STATICDIR;
    }
}
```
In above, I added `fastcgi_param SERVER_NAME $host;` line.

If this change won't invite inconvenience such as security risk, I'll update the documentation.

**Comment by dverdin** [comment]
Sorry, no clue about nginx.
However, @racke knows the tool well if I recall correctly.
I'll request a review from him.

**Comment by ldidry** [comment]
On Debian Stretch, `/etc/nginx/fastcgi_params` contains 
```
fastcgi_param  SERVER_NAME        $server_name;
```

Can you tell us what `/etc/nginx/fastcgi_params` contains on your system?

**Comment by racke** [comment]
Yes, the `$server_name` variable is the correct one.

**Comment by ikedas** [comment]
That's right also with RPM.  I mean `/etc/nginx/conf.d/sympa.conf` would contain lines:
```code
...
    location /sympa {
        include       /etc/nginx/fastcgi_params;
        fastcgi_pass  unix:/var/run/sympa/wwsympa.socket;

        # If you changed wwsympa_url in sympa.conf, change this regex too!
        fastcgi_split_path_info ^(/sympa)(.*)$;
        fastcgi_param SCRIPT_FILENAME /usr/libexec/sympa/wwsympa.fcgi;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SERVER_NAME $host;                            ←Addition
    }
...
```
to override definition of `SERVERNAME` in `fastcgi_params`.

**Comment by ikedas** [comment]
Side note:

I feel a line
```code
fastcgi_param SERVER_NAME $http_host;
```
is not a good idea: Client may set arbitrary `Host:` request field (or no field) and Sympa will trust in it.

`$host` is determined "_in this order of precedence: host name from the request line, or host name from the “Host” request header field, or the server name matching a request_" ([doc](http://nginx.org/en/docs/http/ngx_http_core_module.html#variables)).  Additionally, if HTTPS is enabled, nginx gets SNI host name at first ([ticket](https://trac.nginx.org/nginx/ticket/229)).  It looks safer than `$http_host` for me, but I couldn't be sure.

Another possible way to deteremine virtual hosts using `SERVER_NAME` (defined as `$server_name`) is adding multiple `server` sections.  However I feel it is a bit intricate.

**Comment by racke** [comment]
Multiple server sections could be an alternative and it wouldn't be that intricate, as you can include the sympa part from a include file (actually I doing it that way). You need other settings depending on the server name in the server section (definitely https://).

**Comment by ikedas** [comment]
I see my idea is not so hopeful. I close this issue. Thanks for suggestions!
