### ISSUE TITLE
"Bug" in documentation - postfix: single domain settings

### ISSUE THREAD

**Issue by daoane** [sympa-community/sympa-community.github.io#42]
This report is about a "bug" in the Sympa documentation and refers to page https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html
=> "Single domain setting" => "3. Edit Postfix main.cf":

```
alias_database = (...existing parameter value...), hash:$SYSCONFDIR/aliases.sympa.postfix
```
should read
```
alias_database = (...existing parameter value...), hash:$SYSCONFDIR/aliases.sympa.postfix, hash:$SYSCONFDIR/sympa_transport
```
Without including hash:$SYSCONFDIR/sympa_transport (as on the present documentation page), all incoming messages to any of the mailing lists will be rejected with "Recipient address rejected: User unknown in local recipient table". With hash:$SYSCONFDIR/sympa_transport on the alias_database line, incoming messages are correctly distributed to their respective mailing lists.

**Comment by ikedas** [comment]
I think you mixes two:
  - [Virtual domain setting](https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html#virtual-domain-setting) (using postmap and transports).
  - [Single domain setting](https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html#single-domain-setting) (using postalias and alias database).

With single domain setting, `sympa` and `sympabounce` transports won't be used: Only `local` transport is used.

Anyway I recommend to use virtual domain setting even if you have only one domain to be managed by Sympa.
