### ISSUE TITLE
on fresh install, $SYSCONFDIR and /usr/local/share/sympa/[abl]* should be made writable by sympa

### ISSUE THREAD

**Issue by wfdudley** [sympa-community/sympa-community.github.io#62]
After a fresh install of sympa 6.2.54 on FreeBSD 11.3, the directory /usr/local/etc/sympa 
($SYSCONFDIR) was owned by root:wheel.  This should be changed to root:sympa, 775,
so that sympa may modify the aliases.sympa.sendmail file.  I suggest that sympa_wizard.pl
check for this, since on a new install, the user is supposed to run the wizard.

Also, /usr/local/share/sympa (parent directory of $STATICDIR) has sub directories "arc",
"bounce", and "list_data", and these should also be made writeable by sympa.  Again,
sympa_wizard.pl should check for and fix this.

**Comment by ikedas** [comment]
Hi @wfdudley ,

The bugs you reported look regarding a particular package (FreeBSD port) of Sympa.

Please [submit problem report (PR)(https://www.freebsd.org/support/bugreports.html) to the development team of FreeBSD.

This issue is closed.  Thank you for your effort!

**Comment by wfdudley** [comment]
A smart developer would add the two lines of code to sympa_wizard.pl to make this work regardless of problems with the install scripts on different distributions.  She would also add to the documentation to point out the ownership requirements for these directories.  I guess we don't have those kinds of developers on this project.

**Comment by ikedas** [comment]
Sympa_wizard.pl is planned to be deprecated (see sympa-community/sympa#508).  In the first place, permission of installed file is described in Makefile.am included in source distribution.  Why should we repeat it on the other places?  I guess we have those kind of lazy developers on this project.

**Comment by wfdudley** [comment]
I think that FreeBSD install scripts may have difficulties with setting
permissions correctly.
Mailman comes with a tool that checks the entire install for permission
problems, and will
optionally correct those problems.

I don't know anything about a Makefile.  I install using the FreeBSD pkg
system, and then
I followed the directions in the sympa documentation.  The permissions for
other files
(like the sympa sendmail aliases file)
is mentioned in the documentation, and if this was universally followed, I
wouldn't have
wasted hours wondering why my Sympa install was failing at "create list".

If the developers want people to USE Sympa, then their job is to make it
easy to install
and use.  I'm a fairly experienced UNIX sysadmin, and Perl programmer, and
it took
way to long for me to get the web interface working, and then to get the
permission
problems ironed out.  If it wasn't for the mailing list, I'd have given
up.  If the docs
had covered the permission requirements OR if the wizard (or a program like
it) had
found/fixed those problems, that would have been a huge help.

Bill Dudley

This email is free of malware because I run Linux.

**Comment by ikedas** [comment]
If you wish the things to be changed on this project, please write the code and documentation by yourself, and please submit pull requests (see also [this](https://github.com/sympa-community/sympa/blob/master/CONTRIBUTING.md) and [this](https://github.com/sympa-community/sympa-community.github.io/blob/master/CONTRIBUTING.md)).  Anyways you should understand that the developers are _lazy_ and are _not your srcretaries_.

**Comment by wfdudley** [comment]
Yeah.  I am a retired developer.  I prefer my code to be as fool
proof as possible.

I've got my sympa installation working, though it's not clear I'll
use it.  I've tried to help other sympa installers avoid the problems
I faced.

Thanks for your time.

Oh, and I'm sorry for my snotty tone in the first comment.

Bill Dudley

This email is free of malware because I run Linux.

**Comment by ikedas** [comment]
The developers on Sympa project focus on Sympa itself, but not on the issues specific to packaging for particular environment.

You know that problem of directory permission is the problem of FreeBSD package, and you should [report problem to development team of FreeBSD](https://www.freebsd.org/support/bugreports.html). I think it's the best way to help other Sympa installers from this issue.

**Comment by ikedas** [comment]
Taken over by [FreeBSD Bug 246702](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246702)
