### ISSUE TITLE
Website: dead links and missing users on "Hosting services / Services d'hébergement"

### ISSUE THREAD

**Issue by RainerBielefeld** [sympa-community/sympa-community.github.io#70]
This page contains some dead links
###Not existing hosting services   

- [inViVo](http://sympa.invivo.net/wws/lists) : Error 404  
- International Federation of Library Associations and Institutions : Server not found  
- Unesco : Page load error
- geneve.ch : Server not found
- Le Ministère des Affaires Étrangères: Server not found  
- Education.gouv.fr  : Page load error
- Ministère des finances : Server not found
- Correo Facultad de Ingenieria : Error 404
- Universität Graz : Addressnot found  
and so on.  

All items highlighted yellow or red in [this list](https://rrbd.files.wordpress.com/2020/09/2020-09-02_901_hostingservices_2.pdf) have problems with hte hyperlinks. Mostly: error 404.

### Missing hosters

- "Technische Universätät Braunschweig" offers several sympa lists on https://lists.tu-braunschweig.de/sympa/lists

**Comment by racke** [comment]
@RainerBielefeld This page is not hosted by the Sympa community. Please contact Renater. 

On the other hand I would love to maintain an up-to-date list of organizations using Sympa :smile:.

**Comment by RainerBielefeld** [comment]
I forgot to mention URL of page: https://www.sympa.org/users/custom?s[]=hosting

Yes, hoster is Renater

But I definitively will not do any additional activity for this issue. If "the sympa community" ist not interested in a presentation on a webiste which is up to date, I am not, too.

**Comment by racke** [comment]
We are interested but we have zero control about https://www.sympa.org/. It is an unfortunate situation for us to say the least.

**Comment by dverdin** [comment]
Er... As far as I remember, you're supposed to have control on this site. I remember accounts were created something like one or two years ago. Soji certainly edited some parts of the site.
Did something change,

**Comment by dverdin** [comment]
You're even supposed to have shell access to the server.

**Comment by racke** [comment]
@dverdin Please contact me per private email.

**Comment by dverdin** [comment]
Coming!

**Comment by dverdin** [comment]
hi @RainerBielefeld !
Just so you know : I'm currently fixing the dead links in the page you reported.

Thanks a lot for helping us improve the web site!

David

**Comment by ikedas** [comment]
No updates. Close.
