### ISSUE TITLE
Sympa Amazon AMI

### ISSUE THREAD

**Issue by petergorla** [sympa-community/sympa-community.github.io#73]
Hi, does anyone have a functional instance of Sympa on an Amazon AMI that they would be willing to share? Thanks!

**Comment by ikedas** [comment]
Hi @petergorla ,

Please check [this post](https://listes.renater.fr/sympa/arcsearch_id/sympa-users/2022-04/Sympa_de_AMI.20220401%40conversion.co.jp).
