### ISSUE TITLE
Shared_feature sympa.conf  6.2.40 version.

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa-community.github.io#75]
> The shared_feature off into sympa.conf is not accepted with 6.2.40 version.
> How can i disable the shared repositories options for all users?

@ikedas how can i submit it ?

_Originally posted by @khaoula-abaidi in https://github.com/sympa-community/sympa/issues/872#issuecomment-729512805_

**Comment by ikedas** [comment]
sympa-community/sympa-community.github.io is the project about documentation of Sympa.  Please go to [Issues of sympa-community/sympa](https://github.com/sympa-community/sympa/issues) and submit the new issue.

**Comment by khaoula-abaidi** [comment]
> sympa-community/sympa-community.github.io is the project about documentation of Sympa. Please go to [Issues of sympa-community/sympa](https://github.com/sympa-community/sympa/issues) and submit the new issue.
Done: https://github.com/sympa-community/sympa/issues/1035  thanks
