### ISSUE TITLE
Dead Links on page "Hosting services / Services d'hébergement"

### ISSUE THREAD

**Issue by RainerBielefeld** [sympa-community/sympa-community.github.io#82]
On [Hosting services / Services d'hébergement](https://www.sympa.org/users/custom) there are lots of dead links, see attachment"
In attachment those not working links are higlighted yellow or red.
[NotWorkingLinks.odt](https://github.com/sympa-community/sympa-community.github.io/files/7016309/NotWorkingLinks.odt)

**Comment by racke** [comment]
Please contact Renater about these errors. The sympa.org website is not part of the Sympa community.
