### ISSUE TITLE
Typo in master.cf for automatic list configuration

### ISSUE THREAD

**Issue by simonelbaz** [sympa-community/sympa-community.github.io#93]
Hi,

As mentionned in https://lists.sympa.community/arc/fr/2015-07/msg00027.html, recipient should be used instead of user.

**Comment by simonelbaz** [comment]
May I propose a PR to fix the issue ?

Thanks

**Comment by ikedas** [comment]
@simonelbaz , thank you for reporting bug in the documentation!

No PR is needed this time. Instead, just to be sure, could you confirm the following?

  * After replacing `${user}` in `master.cf` with `${recipient}`, try to send to multiple automatic addresses. e.g.
    `To: auto-aaa@lists.domain.com, auto-bbb@lists.domain.com`

Will both automatic lists be successfully created?  If they won't (only one or none of them were created), maybe following lines have to be added into `main.cf`.
``` code
sympabounce_destination_recipient_limit = 1
sympafamily_destination_recipient_limit = 1
sympa_destination_recipient_limit = 1
```
Could you please confirm whether thses lines are needed or not?

**Comment by simonelbaz** [comment]
The test is:

```
debian@sympa02:~$ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 sympa02.domain.com ESMTP Postfix (Debian/GNU)      
ehlo test
250-sympa02.domain.com      
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
mail from: <test@domain.com>                  
250 2.1.0 Ok
rcpt to: <listespersonnelles-uid7-grp7@lists.domain.com>       
250 2.1.5 Ok
rcpt to: <listespersonnelles-uid8-grp8@lists.domain.com>       
250 2.1.5 Ok
data
354 End data with <CR><LF>.<CR><LF>
subject: test7

test7.
.
250 2.0.0 Ok: queued as 5EB736063B 
```

Sympa logs show:

```
sympa-web-21_1  | Aug 23 12:15:53 sympa-web-21 postfix/pipe[315]: 9AC6F60652: to=<listespersonnelles-uid7-grp7@lists.domain.com>, relay=sympafamilylistespersonnelles, delay=0.04, delays=0.02/0.01/0/0.01, dsn=5.3.0, status=bounced (command line usage error. Command output: /usr/local/libexec/familyqueue: usage error, two arguments expected : list-name family-name ) 
```

Do you want more info ?

Apparently, more than 1 recipient is not allowed by  /usr/local/libexec/familyqueue.

**Comment by simonelbaz** [comment]
I finally understtod your question :)

Yes, with:

```
sympabounce_destination_recipient_limit = 1
sympafamily_destination_recipient_limit = 1
sympa_destination_recipient_limit = 1
```

```
debian@sympa02:~$ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 sympa02.domain.com ESMTP Postfix (Debian/GNU)      
ehlo test
250-sympa02.domain.com      
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
mail from: <test@domain.com>                  
250 2.1.0 Ok
rcpt to: <listespersonnelles-uid16-grp1@lists.domain.com>       
250 2.1.5 Ok
rcpt to: <listespersonnelles-uid16-grp2@lists.domain.com>       
250 2.1.5 Ok
data
354 End data with <CR><LF>.<CR><LF>
subject: test16

test
.
250 2.0.0 Ok: queued as 1CF8160654 
```

Result:
```
sympa-web-21_1  | Aug 24 16:16:43 sympa-web-21 postfix/pipe[294]: A960660656: to=<listespersonnelles-uid16-grp1@lists.domain.com>, relay=sympafamilylistespersonnelles, delay=1, delays=0.02/0.01/0/1, dsn=2.0.0, status=sent (delivered via sympafamilylistespersonnelles service (list-name:listespersonnelles-uid16-grp1@lists.domain.com, family-name:listespersonnelles))       
sympa-web-21_1  | Aug 24 16:16:43 sympa-web-21 postfix/pipe[295]: A960660656: to=<listespersonnelles-uid16-grp2@lists.domain.com>, relay=sympafamilylistespersonnelles, delay=1, delays=0.02/0.02/0/1, dsn=2.0.0, status=sent (delivered via sympafamilylistespersonnelles service (list-name:listespersonnelles-uid16-grp2@lists.domain.com, family-name:listespersonnelles)) 
```

Mails are sent.

**Comment by ikedas** [comment]
Thanks for confirming my concern.   I corrected the documentation: e3d869d

If there are no problems, please feel free to close this issue.  Thanks again!

**Comment by simonelbaz** [comment]
Thanks @ikedas .
I am trying to understand the sympabounce role.
From the bounce documentation (https://www.postfix.org/bounce.8.html), bounce notifies the sender with a delivery status information.

Should the sympabounce send the delivery status information to the user (and not the recipient) ?

Thanks

**Comment by ikedas** [comment]
`sympabounce` transport uses `bouncequeue` program.  It is not related to `bounce(8)` daemon of Postfix.

`sympabounce` transport aims saving bounce messages into bounce spool (`$SPOOLDIR/bounce`).  `bounced.pl` daemon of Sympa picks up and analyzes these messages to execute [bounce management](https://www.sympa.community/manual/customize/bounce-management.html).
